name: lsst-data-challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - python<3.12
  - astropy=7.0.2
  - jupyter=1.1.1
  - pandas=2.2.3
  - pip=25.1.1
  - seaborn=0.13.2
  - scipy=1.15.2
  - tqdm=4.67.1
  - pip:
    - h5py==3.13.0
    - lenstronomy==1.13.0
    - corner==2.2.3
    - keras==3.10.0
    - tensorflow==2.19.0
    - tensorflow-probability==0.25.0